Fix broken CI and some tests (#1279)
Summary:
Fix broken CI and tests
- Remove python3.6 runs for gha which was broken due to pil upgrade
- remove CompleteInTimeOrDie as caffe2 imports not supported from pytorch anymore
- upgrades torch* dependencies since the older versions were leading to this failure : AttributeError: module 'distutils' has no attribute 'version'
- fix test_vilbert and test_visualbert asserts on masked lm loss to check for nan. if all labels contain ignore_index, ce loss returns nan.
- in lightning/test_checkpoint.py, skip 2 tests which were causing gha to crash (idk why) and fix test_load_trainer_ckpt_number_of_step to assert on correct values

Pull Request resolved: https://github.com/facebookresearch/mmf/pull/1279

Test Plan: CI is green now

Reviewed By: ebsmothers

Differential Revision: D42136841

Pulled By: ankitade

fbshipit-source-id: 8d802c5df559949ddb628ee043a9935be3dd71eb